package inf.saveanimals.domain.areas;

import lombok.Getter;

/**
 * 지역구 정보 데이터
 */

@Getter
public enum City {


    // 서울
    GANGNAM_GU("강남구"),
    GANGDONG_GU("강동구"),
    GANGBUK_GU("강북구"),
    SEOUL_GANGSEO_GU("강서구"),
    GWANAK_GU("관악구"),
    GWANGJIN_GU("광진구"),
    GURO_GU("구로구"),
    GEUMCHEON_GU("금천구"),
    NOWON_GU("노원구"),
    DOBONG_GU("도봉구"),
    DONGDAEMUN_GU("동대문구"),
    DONGJAK_GU("동작구"),
    MAPO_GU("마포구"),
    SEODAEMUN_GU("서대문구"),
    SEOCHO_GU("서초구"),
    SEONGDONG_GU("성동구"),
    SEONGBUK_GU("성북구"),
    SONGPA_GU("송파구"),
    YANGCHEON_GU("양천구"),
    YEONGDEUNGPO_GU("영등포구"),
    YONGSAN_GU("용산구"),
    EUNPYEONG_GU("은평구"),
    JONGNO_GU("종로구"),
    SEOUL_JUNG_GU("중구"),
    JUNGNANG_GU("중랑구"),

    // 부산
    BUSAN_GANGSEO_GU("강서구"),
    GEUMJEONG_GU("금정구"),
    GIJANG_GUN("기장군"),
    BUSAN_NAM_GU("남구"),
    BUSAN_DONG_GU("동구"),
    DONGNAE_GU("동래구"),
    BUSANJIN_GU("부산진구"),
    BUSAN_BUK_GU("북구"),
    SASANG_GU("사상구"),
    SAHA_GU("사하구"),
    BUSAN_SEO_GU("서구"),
    SUYEONG_GU("수영구"),
    YEONJE_GU("연제구"),
    YEONGDO_GU("영도구"),
    BUSAN_JUNG_GU("중구"),
    HAEUNDAE_GU("해운대구"),

    // 대구
    GUNWI_GUN("군위군"),
    DAEGU_NAM_GU("남구"),
    DALSEO_GU("달서구"),
    DALSEONG_GUN("달성군"),
    DAEGU_DAEGU_DONG_GU("동구"),
    DAEGU_DAEGU_BUK_GU("북구"),
    DAEGU_DAEGU_SEO_GU("서구"),
    SUSEONG_GU("수성구"),
    DAEGU_JUNG_GU("중구"),

    // 인천
    GANGHWA_GUN("강화군"),
    GYERYANG_GU("계양구"),
    NAMDONG_GU("남동구"),
    INCHEON_DONG_GU("동구"),
    MICHUHOL_GU("미추홀구"),
    BUPYEONG_GU("부평구"),
    INCHEON_SEO_GU("서구"),
    YEONSU_GU("연수구"),
    ONGJIN_GUN("옹진구"),
    INCHEON_JUNG_GU("중구"),

    // 광주
    GWANGSAN_GU("광산구"),
    GWANGJU_NAM_GU("남구"),
    GWANGJU_DONG_GU("동구"),
    GWANGJU_BUK_GU("북구"),
    GWANGJU_SEO_GU("서구"),

    // 세종
    SEJONG("세종특별자치시"),

    // 대전
    DAEDEOK_GU("대덕구"),
    DAEJEON_DONG_GU("동구"),
    DAEJEON_SEO_GU("서구"),
    YUSEONG_GU("유성구"),
    DAEJEON_JUNG_GU("중구"),

    // 울산
    ULSAN_NAM_GU("남구"),
    ULSAN_DONG_GU("동구"),
    ULSAN_BUK_GU("북구"),
    ULJU_GUN("울주군"),
    ULSAN_JUNG_GU("중구"),

    // 경기도
    GAPYEONG_GUN("가평군"),
    GOYANG_SI("고양시"),
    GWAECHEON_SI("과천시"),
    GWANGMYEONG_SI("광명시"),
    GWANGJU_SI("광주시"),
    GURI_SI("구리시"),
    GUNPO_SI("군포시"),
    GIMPO_SI("김포시"),
    NAMYANGJU_SI("남양주시"),
    DONGDUCHEON_SI("동두천시"),
    BUCHEON_SI("부천시"),
    SEONGNAM_SI("성남시"),
    SUWON_SI("수원시"),
    SIHEUNG_SI("시흥시"),
    ANSAN_SI("안산시"),
    ANSEONG_SI("안성시"),
    ANYANG_SI("안양시"),
    YANGJU_SI("양주시"),
    YANGPYEONG_GUN("양평군"),
    YEOJU_SI("여주시"),
    YEONCHEON_GUN("연천군"),
    OSAN_SI("오산시"),
    YONGIN_SI("용인시"),
    YONGIN_SI_GIHEUNGGU("용인시기흥구"),
    UIWANG_SI("의왕시"),
    UIJEONGBU_SI("의정부시"),
    ICHEON_SI("이천시"),
    PAJU_SI("파주시"),
    PYEONGTAEK_SI("평택시"),
    POCHON_SI("포천시"),
    HANAM_SI("하남시"),
    HWASEONG_SI("화성시"),

    // 강원
    GANGNEUNG_SI("강릉시"),
    GANGWON_GOSEONG_GUN("고성군"),
    DONGHAE_SI("동해시"),
    SAMCHEOK_SI("삼척시"),
    SOKCHO_SI("속초시"),
    YANGGU_GUN("양구군"),
    YANGYANG_GUN("양양군"),
    YEONGWOL_GUN("영월군"),
    WONJU_SI("원주시"),
    INJE_GUN("인제군"),
    JEONGSEON_GUN("정선군"),
    CHEORWON_GUN("철원군"),
    CHUNCHEON_SI("춘천시"),
    TAEBAEK_SI("태백시"),
    PYEONGCHANG_GUN("평창군"),
    HONGCHEON_GUN("홍천군"),
    HWACHEON_GUN("화천군"),
    HOENGSEONG_GUN("횡성군"),

    // 충청북도
    GOESAN_GUN("괴산군"),
    DANYANG_GUN("단양군"),
    BOEUN_GUN("보은군"),
    YEONGDONG_GUN("영동군"),
    OKCHEON_GUN("옥천군"),
    EUMSEONG_GUN("음성군"),
    JECHEON_SI("제천시"),
    JEUNGPYEONG_GUN("증평군"),
    JINCHEON_GUN("진천군"),
    CHEONGJU_SI("청주시"),
    CHUNGJU_SI("충주시"),

    // 충청남도
    GYERYONG_SI("계룡시"),
    GONGJU_SI("공주시"),
    GEUMSAN_GUN("금산군"),
    NONSAN_SI("논산시"),
    DANGJIN_SI("당진시"),
    BORYEONG_SI("보령시"),
    BUYEO_GUN("부여군"),
    SEOSAN_SI("서산시"),
    SEOCHEON_GUN("서천군"),
    ASAN_SI("아산시"),
    YEONKI_GUN("연기군"),
    YESAN_GUN("예산군"),
    CHEONAN_SI("천안시"),
    CHEONGYANG_GUN("청양군"),
    TAEAN_GUN("태안군"),
    HONGSEONG_GUN("홍성군"),

    // 전라북도
    GOCHANG_GUN("고창군"),
    GUNSAN_SI("군산시"),
    GIMJE_SI("김제시"),
    NAMWON_SI("남원시"),
    MUJU_GUN("무주군"),
    BUAN_GUN("부안군"),
    SUNCHANG_GUN("순창군"),
    WANJU_GUN("완주군"),
    IKSAN_SI("익산시"),
    IMSIL_GUN("임실군"),
    JANGSU_GUN("장수군"),
    JEONJU_SI("전주시"),
    JEONGEUP_SI("정읍시"),
    JINAN_GUN("진안군"),

    // 전라남도
    GANGJIN_GUN("강진군"),
    GOHEUNG_GUN("고흥군"),
    GOKSEONG_GUN("곡성군"),
    GWANGYANG_SI("광양시"),
    GURYE_GUN("구례군"),
    NAJU_SI("나주시"),
    DAMYANG_GUN("담양군"),
    MOKPO_SI("목포시"),
    MUAN_GUN("무안군"),
    BOSEONG_GUN("보성군"),
    SUNGCHEON_SI("순천시"),
    SINAN_GUN("신안군"),
    YEOSU_SI("여수시"),
    YEONGGWANG_GUN("영광군"),
    WANDO_GUN("완도군"),
    JANGSEONG_GUN("장성군"),
    JANGHEUNG_GUN("장흥군"),
    JINDO_GUN("진도군"),
    HAMPYEONG_GUN("함평군"),
    HAENAM_GUN("해남군"),
    HWASUN_GUN("화순군"),

    // 경상북도
    GYEONGSAN_SI("경산시"),
    GYEONGJU_SI("경주시"),
    GORYEONG_GUN("고령군"),
    GUMI_SI("구미시"),
    GIMCHEON_SI("김천시"),
    MOONKYUNG_SI("문경시"),
    BONGHWA_GUN("봉화군"),
    SANGJU_SI("상주시"),
    SEONGJU_GUN("성주군"),
    ANDONG_SI("안동시"),
    YEONGDEOK_GUN("영덕군"),
    YEONGYANG_GUN("영양군"),
    YEONGJU_SI("영주시"),
    YEONGCHUN_SI("영천시"),
    YECHON_GUN("예천군"),
    ULLEUNG_GUN("울릉군"),
    ULJIN_GUN("울진군"),
    UISEONG_GUN("의성군"),
    CHEONGDO_GUN("청도군"),
    CHEONGSONG_GUN("청송군"),
    CHILGOK_GUN("칠곡군"),
    POHANG_SI("포항시"),

    // 경상남도
    GEOJE_SI("거제시"),
    GEOCHANG_GUN("거창군"),
    GYEONGSANGNAM_GOSEONG_GUN("고성군"),
    GIMHAE_SI("김해시"),
    NAMHAE_GUN("남해군"),
    MIRYANG_SI("밀양시"),
    SACHEON_SI("사천시"),
    SANSCHEONG_GUN("산청군"),
    YANGSAN_SI("양산시"),
    UIRYEONG_GUN("의령군"),
    JINJU_SI("진주시"),
    CHANGNYEONG_GUN("창녕군"),
    CHANGWON_MASANHAPPOHOEWEON_GU("창원마산합포회원구"),
    CHANGWON_SINGISAN_GU("창원의창성산구"),
    CHANGWON_JINHAE_GU("창원진해구"),
    TONGYEONG_SI("통영시"),
    HADONG_GUN("하동군"),
    HAMAN_GUN("함안군"),
    HAMYANG_GUN("함양군"),
    HAPCHEON_GUN("합천군"),

    // 제주
    JEJU_SI("제주시"),
    SEOGWIPO_SI("서귀포시");
    private String kCode;

   City(String kCode) {
       this.kCode = kCode;
   }

}
