package inf.saveanimals.domain.animals.common;

import lombok.Getter;

// 모든 품종
@Getter
public enum Breed {

    // Dog breeds
    GOLDEN_RETRIEVER( "골든 리트리버"),
    GREYHOUND( "그레이 하운드"),
    GREAT_DANE( "그레이트 덴"),
    GREAT_PYRENEES( "그레이트 피레니즈"),

    COTON_DE_TULEAR( "꼬똥 드 뚤레아"),
    NEAPOLITAN_MASTIFF( "네오폴리탄 마스티프"),
    NORFOLK_TERRIER( "노르포크 테리어"),
    NORWICH_TERRIER( "노리치 테리어"),
    NORFOLK_TERRIER_2( "노퍽 테리어"),
    NEWFOUNDLAND( "뉴펀들랜드"),
    DACHSHUND( "닥스훈트"),
    DALMATIAN( "달마시안"),
    DANDIE_DINMONT_TERRIER( "댄디 딘몬트 테리어"),
    DOGO_CANARIO( "도고 까니리오"),
    DOGO_ARGENTINO( "도고 아르젠티노"),

    DOBERMAN("도베르만"),
    TOSA( "도사"),
    TOSA_MIX( "도사 믹스견"),
    DONGGYEONG_DOG( "동경견"),
    LABRADOR_RETRIEVER( "라브라도 리트리버"),
    LHASA_APSO( "라사 압소"),
    LAIKA( "라이카"),
    RABBIT_DACHSHUND( "래빗 닥스훈드"),
    RAT_TERRIER( "랫 테리어"),
    LAKELAND_TERRIER( "레이크랜드 테리어"),
    RHODESIAN_RIDGEBACK("로디지안 리즈백"),
    ROTTWEILER( "로트와일러"),
    ROTTWEILER_MIX( "로트와일러 믹스견"),
    MALINOIS( "마리노이즈"),
    MASTIFF( "마스티프"),
    MALAMUTE( "말라뮤트"),
    MALTESE( "말티즈"),
    MANCHESTER_TERRIER( "맨체스터테리어"),
    MINIATURE_DACHSHUND( "미니어쳐 닥스훈트"),
    MINIATURE_BULL_TERRIER( "미니어쳐 불 테리어"),
    MINIATURE_SCHNAUZER( "미니어쳐 슈나우저"),
    MINIATURE_POODLE( "미니어쳐 푸들"),
    MINIATURE_PINSCHER("미니어쳐 핀셔"),
    MEDIUM_POODLE( "미디엄 푸들"),
    MITTEL_SPITZ( "미텔 스피츠"),
    BASENJI( "바센지"),
    BASSET_HOUND( "바셋 하운드"),
    BERNESE_MOUNTAIN_DOG( "버니즈 마운틴 독"),
    BEDLINGTON_TERRIER( "베들링턴 테리어"),
    BELGIAN_GROENENDAEL( "벨기에 그로넨달"),
    BELGIAN_SHEEPDOG("벨기에 쉽독"),
    BELGIAN_TERVUREN( "벨기에 테뷰런"),
    BELGIAN_SHEPHERD( "벨지안 셰퍼드 독"),
    BORDER_COLLIE( "보더 콜리"),
    BORZOI( "보르조이"),
    BOSTON_TERRIER( "보스턴 테리어"),
    BOXER( "복서"),
    BOLOGNESE( "볼로네즈"),
    BOUVIER_DES_FLANDRES( "부비에 데 플랑드르"),
    BULL_TERRIER("불 테리어"),
    BULLDOG("불독"),
    BRUSSELS_GRIFFON( "브뤼셀그리펀"),
    BRITTANY_SPANIEL( "브리타니 스파니엘"),
    BLACK_TERRIER("블랙 테리어"),
    BEAGLE( "비글"),
    BICHON_FRISE( "비숑 프리제"),
    BEARDED_COLLIE( "비어디드 콜리"),
    VIZSLA( "비즐라"),
    PAPILLON("빠삐용"),
    SAMOYED( "사모예드"),
    SALUKI( "살루키"),
    SAPSAL( "삽살개"),
    SHAR_PEI( "샤페이"),
    SAINT_BERNARD( "세인트 버나드"),
    CENTRAL_ASIAN_OVTCHARKA( "센트럴 아시안 오브차카"),
    SHETLAND_SHEEPDOG( "셔틀랜드 쉽독"),
    SHEPHERD( "셰퍼드"),
    SCHNAUZER( "슈나우져"),
    SCOTTISH_TERRIER( "스코티쉬 테리어"),
    SCOTTISH_DEERHOUND( "스코티시 디어하운드"),
    STAFFORDSHIRE_BULL_TERRIER("스태퍼드셔 불 테리어"),
    STAFFORDSHIRE_BULL_TERRIER_MIX( "스태퍼드셔 불 테리어 믹스견"),
    STANDARD_POODLE( "스탠다드 푸들"),
    SPITZ( "스피츠"),
    SHIBA( "시바"),
    SIBERIAN_HUSKY( "시베리안 허스키"),
    SIBERIAN_LAIKA( "시베리안라이카"),
    SEEING_FRANCAISE( "시잉프랑세즈"),
    SHIH_TZU( "시츄"),
    SHIKOKU( "시코쿠"),
    SEALYHAM_TERRIER( "실리햄 테리어"),
    SILKY_TERRIER( "실키테리어"),
    ANATOLIAN_SHEPHERD( "아나톨리안 셰퍼드"),
    AMERICAN_BULLDOG( "아메리칸 불독"),
    AMERICAN_STAFFORDSHIRE_TERRIER( "아메리칸 스태퍼드셔 테리어"),
    AMERICAN_STAFFORDSHIRE_TERRIER_MIX( "아메리칸 스태퍼드셔 테리어 믹스견"),
    AMERICAN_AKITA("아메리칸 아키다"),
    AMERICAN_ESKIMO( "아메리칸 에스키모"),
    AMERICAN_COCKER_SPANIEL("아메리칸 코카 스파니엘"),
    AMERICAN_PIT_BULL_TERRIER( "아메리칸 핏불 테리어"),
    AMERICAN_PIT_BULL_TERRIER_MIX( "아메리칸 핏불 테리어 믹스견"),
    AMERICAN_BULLY( "아메리칸불리"),
    IRISH_RED_AND_WHITE_SETTER( "아이리쉬 레드 앤 화이트 세터"),
    IRISH_SETTER( "아이리쉬 세터"),
    IRISH_WOLF_HOUND( "아이리쉬 울프 하운드"),
    IRISH_SOFT_COATED_WHEATEN_TERRIER( "아이리쉬소프트 코티드 휘튼 테리어"),
    AKITA("아키다"),
    AFGHAN_HOUND( "아프간 하운드"),
    ALASKAN_MALAMUTE("알라스칸 말라뮤트"),
    AIREDALE_TERRIER( "에어델 테리어"),
    OVCHARKA("오브차카"),
    AUSTRALIAN_SHEPHERD( "오스트랄리안 셰퍼드 독"),
    AUSTRALIAN_CATTLE_DOG("오스트랄리안 캐틀 독"),
    AUSTRALIAN_KELPIE("오스트레일리안 켈피"),
    OLD_ENGLISH_BULLDOG("올드 잉글리쉬 불독"),
    OLD_ENGLISH_SHEEPDOG("올드 잉글리쉬 쉽독"),
    WEIMARANER("와이마라너"),
    WIRE_FOX_TERRIER("와이어 폭스 테리어"),
    YORKSHIRE_TERRIER("요크셔 테리어"),
    WOLFDOG("울프독"),
    WEST_SIBERIAN_LAIKA("웨스트 시베리언 라이카"),
    WEST_HIGHLAND_WHITE_TERRIER("웨스트하이랜드화이트테리어"),
    WELSH_CORGI_CARDIGAN("웰시 코기 카디건"),
    WELSH_CORGI_PEMBROKE("웰시 코기 펨브로크"),
    WELSH_TERRIER("웰시 테리어"),
    ITALIAN_GREYHOUND("이탈리안 그레이 하운드"),
    ENGLISH_SETTER("잉글리쉬 세터"),
    ENGLISH_SPRINGER_SPANIEL("잉글리쉬 스프링거 스파니엘"),
    ENGLISH_COCKER_SPANIEL("잉글리쉬 코카 스파니엘"),
    ENGLISH_POINTER("잉글리쉬 포인터"),
    GIANT_SCHNAUZER("자이언트 슈나우져"),
    JAPANESE_SPITZ("재패니즈 스피츠"),
    JACK_RUSSELL_TERRIER("잭 러셀 테리어"),
    GERMAN_SHEPHERD("저먼 셰퍼드 독"),
    GERMAN_WIREHAIRED_POINTER("저먼 와이어헤어드 포인터"),
    GERMAN_POINTER("저먼 포인터"),
    GERMAN_HUNTING_TERRIER("저먼 헌팅 테리어"),
    JEJU_DOG("제주개"),
    JAPANESE_CHIN("제페니즈칭"),
    JINDO("진도견"),
    CHOW_CHOW("차우차우"),
    CHINESE_CRESTED_DOG("차이니즈 크레스티드 독"),
    CHIHUAHUA("치와와"),
    CANE_CORSO("카네 코르소"),
    KARELIAN_BEAR_DOG("카레리안 베어독"),
    KAI("카이훗"),
    CAVALIER_KING_CHARLES_SPANIEL("캐벌리어 킹 찰스 스파니엘"),
    KENNELSPANIEL("케니스펜더"),
    KERRY_BLUE_TERRIER("케리 블루 테리어"),
    KEESHOND("케이스훈드"),
    TOY_MANCHESTER_TERRIER("토이 맨체스터 테리어"),
    TOY_POODLE("토이 푸들"),
    TIBETAN_MASTIFF("티베탄 마스티프"),
    PHARAOH_HOUND("파라오 하운드"),
    PARSON_RUSSELL_TERRIER("파슨 러셀 테리어"),
    PALEN("팔렌"),
    PUG("퍼그"),
    PEKINGESE("페키니즈"),
    PETIT_BASSET_GRIFFON_VENDEEN("페테데일테리어"),
    POMERANIAN("포메라니안"),
    POINTER("포인터"),
    FOX_TERRIER("폭스테리어"),

    POODLE("푸들"),
    PULI("풀리"),
    PUNGSAN_DOG("풍산견"),
    PRESA_CANARIO("프레사까나리오"),
    FRENCH_BULLDOG("프렌치 불독"),
    FRENCH_BRITTANY("프렌치 브리타니"),
    FLAT_COATED_RETRIEVER("플랫 코티드 리트리버"),
    PLOTT_HOUND("플롯하운드"),
    PYRENEAN_MASTIFF("피레니안 마운틴 독"),
    FILA_BRASILEIRO("필라 브라질레이로"),
    PIT_BULL_TERRIER("핏불테리어"),
    PIT_BULL_TERRIER_MIX("핏불테리어 믹스견"),
    HAVANESE("허배너스"),
    WHITE_RETRIEVER("화이트리트리버"),
    WHITE_TERRIER("화이트테리어"),
    WHIPPET("휘펫"),
    MIXED_DOG_BREED( "믹스견"),

    // 고양이
    NORWEGIAN_FOREST("노르웨이 숲"),
    NEBELUNG("니벨룽"),
    DEVON_REX("데본 렉스"),
    RUSSIAN_BLUE("러시안 블루"),
    RAGDOLL("레그돌"),
    RAGDOLL_RAGAMUFFIN("레그돌-라가머핀"),
    MANX("맹크스"),
    MUNCHKIN("먼치킨"),
    MAINE_COON("메인쿤"),
    BALINESE("발리네즈"),
    BURMESE("버만"),
    BENGAL("벵갈"),
    BOMBAY("봄베이"),
    BRITISH_LONGHAIR("브리티쉬롱헤어"),
    BRITISH_SHORTHAIR("브리티쉬 쇼트헤어"),
    BIRMAN("버먼"),
    CHARTREUX("샤트룩스"),
    SIAMESE("샴"),
    SELKIRK_REX("셀커크 렉스"),
    SOMALI("소말리"),
    SNOW_SHOE("스노우 슈"),
    SCOTTISH_FOLD("스코티시 폴드"),
    SPHYNX("스핑크스"),
    SIBERIAN_FOREST("시베리안 포레스트"),
    SINGAPURA("싱가푸라"),
    AMERICAN_SHORTHAIR("아메리칸 쇼트헤어"),
    ABYSSINIAN("아비시니안"),
    JAPANESE_BOBTAIL("재패니즈 밥테일"),
    TURKISH_ANGORA("터키시 앙고라"),
    TONKINESE("통키니즈"),
    PERSIAN("페르시안"),
    PERSIAN_CHINCHILLA("페르시안-페르시안 친칠라"),
    HAVANA_BROWN("하바나 브라운"),
    HIGHLAND_FOLD("하이랜드 폴드"),
    KOREAN_SHORTHAIR("코리안숏헤어"),
    MIXED_CAT_BREED( "믹스묘");




    private String kCode;

    Breed(String kCode) {
        this.kCode = kCode;
    }
}
